# Generated by Django 3.1.2 on 2020-10-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201012_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='direction',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(null=True, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='verificate',
            field=models.BooleanField(default=False, verbose_name='Verificado'),
        ),
    ]
