# Generated by Django 3.1.2 on 2020-10-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201015_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Commentario'),
        ),
    ]
