# Generated by Django 3.1.2 on 2020-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201023_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='profile',
            name='municipio',
            field=models.CharField(max_length=100, null=True, verbose_name='Municipio'),
        ),
    ]
