# Generated by Django 3.1.2 on 2020-11-03 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20201029_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(max_length=100, null=True, verbose_name='Genero'),
        ),
    ]
