# Generated by Django 3.1.2 on 2020-11-09 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20201109_1438'),
        ('users', '0012_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.store', verbose_name='Tienda asignada'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=100, null=True, verbose_name='Genero'),
        ),
    ]
