# Generated by Django 3.1.2 on 2020-11-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20201109_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DNI',
            field=models.CharField(max_length=100, null=True, verbose_name='Cedula'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telephone',
            field=models.IntegerField(null=True, verbose_name='Celular'),
        ),
    ]
