# Generated by Django 3.1.2 on 2020-11-16 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20201113_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='defalt.png', upload_to='profile_pics', verbose_name='Imagen'),
        ),
    ]
