# Generated by Django 3.1.2 on 2020-11-17 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201116_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, default='Tu Cuenta está en proceso de verificación', max_length=255, null=True, verbose_name='Commentario'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='profile_pics', verbose_name='Imagen'),
        ),
    ]
