# Generated by Django 3.1.2 on 2020-11-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20201117_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, default='Tu cuenta será verificada en un periodo máximo de 1 hora', max_length=255, null=True, verbose_name='Commentario'),
        ),
    ]
