# Generated by Django 3.1.2 on 2020-11-23 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20201117_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='send_email',
            field=models.BooleanField(default=False, verbose_name='send'),
        ),
    ]
