# Generated by Django 3.1.2 on 2020-11-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_profile_send_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='send_email',
            new_name='sendEmail',
        ),
    ]
