# Generated by Django 3.1.2 on 2020-11-25 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20201123_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, default='Tu cuenta será verificada en un periodo máximo de 1 hora', max_length=1000, null=True, verbose_name='Commentario'),
        ),
    ]
