# Generated by Django 3.1.2 on 2020-12-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20201125_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='comment',
            field=models.CharField(blank=True, default='Tu cuenta será verificada en breve.', max_length=1000, null=True, verbose_name='Commentario'),
        ),
    ]
