"""
Django settings for LaChalupa project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path
import dj_database_url 
from django.conf import global_settings
import environ
#import django_heroku
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATE_CONTEXT_PROCESSORS = ('django.core.context_processors.i18n',)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/
env = environ.Env()
# reading .env file
environ.Env.read_env()
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'xa4v^=ia&h2@oow3mav9^4tz!tn*5*la!7s_=ux@g2x#*ueb5#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
#ALLOWED_HOSTS = ['chalupatona.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'users',
    'registration.apps.RegistrationConfig',
    'game',
    'crispy_forms',
    'django_social_share',
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'material.admin',
    #'material.admin.default',
    #own
    #'webpack_loader',
    'bootstrap4',
    'bootstrap_datepicker_plus',
    'django_static_jquery3',
    'django_static_arrive',
    #'django_cascading_dropdown_widget',
    'whitenoise',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'ip_restriction.IpWhitelister',
    
]

ROOT_URLCONF = 'LaChalupa.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, "templates"),
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            
            ],
        },
    },
]

WSGI_APPLICATION = 'LaChalupa.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env("DATABASE_NAME"),
        'HOST':  env("DATABASE_HOST"),
        'PORT': env("DATABASE_PORT"),
        'USER': env("DATABASE_USER"),
        'PASSWORD': env("DATABASE_PASSWORD"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    
    
    {'NAME': 'users.validators.UppercaseValidator', },
    {'NAME': 'users.validators.NumberValidator', },
    {'NAME': 'users.validators.LowercaseValidator', },
    {'NAME': 'users.validators.SymbolValidator', },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR,'media')
MEDIA_URL = '/media/'
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# Extra lookup directories for collectstatic to find static files


#  Add configuration for static files storage using whitenoise
#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
#django_heroku.settings(locals()) 
CRISPY_TEMPLATE_PACK="bootstrap4"
LOGIN_REDIRECT_URL = "/inicio"
LOGIN_URL = 'login'
LOGOUT_URL = 'logout'
LOGOUT_REDIRECT_URL = "/inicio"
#vue loaders
STATICFILES_DIRS = [
    #os.path.join(BASE_DIR, "assets"),
    #os.path.join(BASE_DIR, "frontend/dist"),
]
BOOTSTRAP4 = {
    'include_jquery': True,
}
##WEBPACK_LOADER = {
#    'DEFAULT': {
#        'BUNDLE_DIR_NAME': 'dist/',
#        'STATS_FILE': os.path.join(BASE_DIR, 'frontend', 'webpack-stats.json')
#    }
#}
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.office365.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER  = 'no-reply@chalupatona.com'
EMAIL_HOST_PASSWORD = 'hmgbldtyltmsxthc'
DEFAULT_FROM_EMAIL = 'Chalupa Toña <no-reply@chalupatona.com>'
##Django Material 
MATERIAL_ADMIN_SITE = {
    'HEADER':  'Chalupa Toña',  # Admin site header
    'TITLE':  'Chalupa Toña',  # Admin site title
    'MAIN_BG_COLOR':  'green',
    'MODEL_ICONS': {  
        'card': 'collections',
        'reward':'loyalty'
    }
}

LANGUAGE_CODE = 'es'
_ = lambda s: s

LANGUAGES = (
 ('es', _('Espanish')),
 ('en', _('English')),
)
USE_I18N = True

USE_L10N = True

USE_TZ = True

