# Generated by Django 3.1.2 on 2020-10-28 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201028_1154'),
        ('registration', '0002_city_department'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Department',
            new_name='Country',
        ),
    ]
