# Generated by Django 3.1.2 on 2020-10-26 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0002_auto_20201014_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(verbose_name='Cantidad')),
                ('type_reward', models.CharField(max_length=255, verbose_name='Tipo')),
                ('description', models.CharField(max_length=255, verbose_name='Descripción')),
                ('image', models.ImageField(upload_to='game_pics', verbose_name='Imagen')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicacion del Premio')),
            ],
        ),
        migrations.CreateModel(
            name='Reward_Verificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicacion')),
                ('reward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.reward', verbose_name='Premio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
