# Generated by Django 3.1.2 on 2020-10-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_reward_reward_verificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reward',
            options={'verbose_name': 'Premio', 'verbose_name_plural': 'Premios'},
        ),
        migrations.AddField(
            model_name='reward',
            name='department',
            field=models.CharField(max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='reward',
            name='municipio',
            field=models.CharField(max_length=100, null=True, verbose_name='Municipio'),
        ),
    ]
