# Generated by Django 3.1.2 on 2020-10-29 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20201028_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cards',
            field=models.CharField(max_length=100, null=True, verbose_name='Carton'),
        ),
        migrations.AddField(
            model_name='game',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Entregado'),
        ),
        migrations.AddField(
            model_name='game',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='game.reward', verbose_name='Premio'),
        ),
        migrations.AlterField(
            model_name='game',
            name='date',
            field=models.DateTimeField(verbose_name='Fecha del Juego'),
        ),
        migrations.AlterField(
            model_name='game',
            name='won',
            field=models.BooleanField(verbose_name='Ganado'),
        ),
    ]
