# Generated by Django 3.1.2 on 2020-10-29 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20201028_1647'),
        ('game', '0006_auto_20201029_1018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='department',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='municipio',
        ),
        migrations.AddField(
            model_name='game',
            name='sing',
            field=models.CharField(max_length=100, null=True, verbose_name='Cantada'),
        ),
        migrations.AddField(
            model_name='reward',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.city', verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='reward',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registration.country', verbose_name='Departamento'),
        ),
    ]
