# Generated by Django 3.1.2 on 2020-11-02 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201029_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='PID',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='delivered',
            field=models.IntegerField(default=0, verbose_name='Entregado'),
        ),
    ]
