# Generated by Django 3.1.2 on 2020-11-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_auto_20201102_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Latiud'),
        ),
        migrations.AddField(
            model_name='reward',
            name='longitude',
            field=models.FloatField(default=0, verbose_name='Longitud'),
        ),
    ]
