# Generated by Django 3.1.2 on 2020-11-03 22:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201103_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.store', verbose_name='Tienda'),
        ),
    ]
