# Generated by Django 3.1.2 on 2020-11-09 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_reward_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='gender',
            field=models.CharField(choices=[('General', 'General'), ('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=100, null=True, verbose_name='Genero'),
        ),
    ]
