# Generated by Django 3.1.2 on 2020-11-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20201109_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='sound',
            field=models.CharField(max_length=100, null=True, verbose_name='Audio'),
        ),
    ]
