# Generated by Django 3.1.2 on 2020-11-12 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_card_sound'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='location',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='type_reward',
        ),
    ]
