# Generated by Django 3.1.2 on 2020-11-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_auto_20201112_0908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reward',
            name='description',
        ),
        migrations.RemoveField(
            model_name='reward',
            name='store',
        ),
        migrations.AddField(
            model_name='reward',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('N/A', 'N/A')], default='N/A', max_length=255, verbose_name='Talla'),
        ),
        migrations.AddField(
            model_name='reward',
            name='type_reward',
            field=models.CharField(choices=[('Camiseta', 'Camiseta'), ('Gorra', 'Gorra'), ('Liquido', 'Liquido'), ('Chalupa', 'Chalupa')], max_length=255, null=True, verbose_name='Tipo'),
        ),
    ]
