# Generated by Django 3.1.2 on 2020-11-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0017_auto_20201117_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='rewards',
            field=models.ManyToManyField(to='game.Reward'),
        ),
    ]
