# Generated by Django 3.1.2 on 2020-11-18 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0018_store_rewards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reward',
            old_name='stock',
            new_name='unit',
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField(verbose_name='Cantidad')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.reward', verbose_name='Premio')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.store', verbose_name='Tienda')),
            ],
            options={
                'verbose_name': 'Inventario',
                'verbose_name_plural': 'Inventario',
            },
        ),
    ]
