# Generated by Django 3.1.2 on 2020-11-18 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0019_auto_20201117_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='rewards',
        ),
    ]
