# Generated by Django 3.1.2 on 2020-11-23 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0020_remove_store_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conteo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.IntegerField(verbose_name='Cantidad')),
            ],
        ),
    ]
