# Generated by Django 3.1.2 on 2020-11-27 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0021_conteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='date_reward',
            field=models.DateTimeField(null=True, verbose_name='Fecha Entrega premio'),
        ),
    ]
