# Generated by Django 3.1.2 on 2020-12-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0023_conteo_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='group',
            field=models.IntegerField(null=True, verbose_name='Grupo'),
        ),
    ]
